### ISSUE TITLE
Rails/RakeEnvironment

### ISSUE THREAD

**Issue by martijnbleeker** [youngcapital/rubocopital#10]
## Rails/RakeEnvironment

Enabled by default | Safe | Supports autocorrection | VersionAdded | VersionChanged
--- | --- | --- | --- | ---
Enabled | No | No | 2.4 | -

This cop checks rake task definition without `environment` dependency.
`environment` dependency is important because it loads application code
for the rake task. The rake task cannot use application code, such as
models, without `environment` dependency.

You can ignore the offense if the task satisfies at least one of the
following conditions:

* The task does not need application code.
* The task invokes :environment task.

### Examples

```ruby
# bad
task :foo do
  do_something
end

# good
task foo: :environment do
  do_something
end
```

### Configurable attributes

Name | Default value | Configurable values
--- | --- | ---
Include | `**/Rakefile`, `**/*.rake` | Array

**Comment by karsthammer** [comment]
Not sure about this one, if you don't depend on `:environment` and it is needed you will find out quickly, and I prefer not to have to override rubocop for tasks that don't need the environment to be loaded.

Also I fear that using this cop might make people add `:environment` all the time even when not needed and that is (really) bad for performance.

**Comment by martijnbleeker** [comment]
Please be aware that this is a rails cop, not a ruby one.
I personally cannot think of an example where there's a rake task that does something useful without needing the environment.

**Comment by karsthammer** [comment]
I'm aware, I just feel that performance-wise it's a bad assumption that every rake task should need `:environment`.

**Comment by Nittarab** [comment]
here yo you an example:

https://github.com/ctran/annotate_models/blob/develop/lib/generators/annotate/templates/auto_annotate_models.rake

The annotate task don't need to load all the environment work but it is very useful
