### ISSUE TITLE
RSpec/ImplicitBlockExpectation

### ISSUE THREAD

**Issue by martijnbleeker** [youngcapital/rubocopital#14]
## RSpec/ImplicitBlockExpectation

Enabled by default | Supports autocorrection
--- | ---
Enabled | No

Check that implicit block expectation syntax is not used.

Prefer using explicit block expectations.

### Examples

```ruby
# bad
subject { -> { do_something } }
it { is_expected.to change(something).to(new_value) }

# good
it 'changes something to a new value' do
  expect { do_something }.to change(something).to(new_value)
end
```

### References

* [https://www.rubydoc.info/gems/rubocop-rspec/RuboCop/Cop/RSpec/ImplicitBlockExpectation](https://www.rubydoc.info/gems/rubocop-rspec/RuboCop/Cop/RSpec/ImplicitBlockExpectation)

**Comment by MarcelEeken** [comment]
I'm conflicted on this one. For all normal tests I fully agree with this, but with shoulda matchers im okay with the single line. For example I'm perfectly fine with the following:
```ruby
  it { is_expected.to validate_presence_of(:name) }
  it { is_expected.to validate_length_of(:name).is_at_most(255) }
```
