### ISSUE TITLE
FactoryBot/FactoryClassName

### ISSUE THREAD

**Issue by martijnbleeker** [youngcapital/rubocopital#17]
## FactoryBot/FactoryClassName

Enabled by default | Supports autocorrection
--- | ---
Enabled | Yes

Use string value when setting the class attribute explicitly.

### Examples

```ruby
# bad
factory :foo, class: Foo do
end

# good
factory :foo, class: 'Foo' do
end
```

### References

* [https://www.rubydoc.info/gems/rubocop-rspec/RuboCop/Cop/RSpec/FactoryBot/FactoryClassName](https://www.rubydoc.info/gems/rubocop-rspec/RuboCop/Cop/RSpec/FactoryBot/FactoryClassName)

**Comment by MarcelEeken** [comment]
May I ask the reasoning behind this cop. A class there seems perfectly fine
