### ISSUE TITLE
Style/DisableCopsWithinSourceCodeDirective

### ISSUE THREAD

**Issue by shannonfuit** [youngcapital/rubocopital#26]
# Style/DisableCopsWithinSourceCodeDirective

Enabled by default | Safe | Supports autocorrection | VersionAdded | VersionChanged
-- | -- | -- | -- | --
Disabled | Yes | Yes | 0.82 | -

Detects comments to enable/disable RuboCop. This is useful if want to make sure that every RuboCop error gets fixed and not quickly disabled with a comment.

### Examples
```ruby
# bad
# rubocop:disable Metrics/AbcSize
def f
end
# rubocop:enable Metrics/AbcSize

# good
def fixed_method_name_and_no_rubocop_comments
end
```

**Comment by MarcelEeken** [comment]
Sometimes it is handy to be able to disable a cop, or the fix is worse than the problem

**Comment by shannonfuit** [comment]
Sometimes Rubocop's suggestion is wrong
=> auto correct `collection.max { |o| o.value }` is autocorrected to `collection.max(&:value)` which breaks in older ruby versions
=> early return in your controller action while your render is not explicitly in the method

**Comment by MarcelEeken** [comment]
That should not actually be a problem. If you configure `TargetRubyVersion` and `TargetRailsVersion` correctly for all cops it knows which cops can apply and which not.

For our project we have that currently configured to:
```
AllCops:
  TargetRubyVersion: 2.7.1
  TargetRailsVersion: 6.0
```

**Comment by risc12** [comment]
I think we are all responsible and professional enough to decide whether a cop is helping or hurting and we have the code-review step in our process so teams can agree on whether disabling is good in the specific cases.
