### ISSUE TITLE
Style/FloatDivision

### ISSUE THREAD

**Issue by martijnbleeker** [youngcapital/rubocopital#3]
## Style/FloatDivision

Enabled by default | Safe | Supports autocorrection | VersionAdded | VersionChanged
--- | --- | --- | --- | ---
Enabled | Yes | No | 0.72 | -

This cop checks for division with integers coerced to floats.
It is recommended to either always use `fdiv` or coerce one side only.
This cop also provides other options for code consistency.

#### EnforcedStyle: single_coerce (default) 😄 

```ruby
# bad
a.to_f / b.to_f

# good
a.to_f / b
a / b.to_f
```
#### EnforcedStyle: left_coerce 🎉 

```ruby
# bad
a / b.to_f
a.to_f / b.to_f

# good
a.to_f / b
```
#### EnforcedStyle: right_coerce 🚀 

```ruby
# bad
a.to_f / b
a.to_f / b.to_f

# good
a / b.to_f
```
#### EnforcedStyle: fdiv 👀 

```ruby
# bad
a / b.to_f
a.to_f / b
a.to_f / b.to_f

# good
a.fdiv(b)
```

### Configurable attributes

Name | Default value | Configurable values
--- | --- | ---
EnforcedStyle | `single_coerce` | `left_coerce`, `right_coerce`, `single_coerce`, `fdiv`

### References

* [https://rubystyle.guide#float-division](https://rubystyle.guide#float-division)
* [https://github.com/rubocop-hq/ruby-style-guide/issues/628](https://github.com/rubocop-hq/ruby-style-guide/issues/628)

**Comment by xtr3me** [comment]
I like it to be more explicit, so `a.to_f / b.to_f`

**Comment by martijnbleeker** [comment]
Since the configuration options are a tie, we will go for the default.
