### ISSUE TITLE
RSpec/VariableDefinition

### ISSUE THREAD

**Issue by shannonfuit** [youngcapital/rubocopital#39]
# RSpec/VariableDefinition

Enabled by default | Safe | Supports autocorrection | VersionAdded | VersionChanged
-- | -- | -- | -- | --
Enabled | Yes | No | 1.40 | -

Checks that memoized helpers names are symbols or strings.

### Examples
EnforcedStyle: symbols (default)
```ruby
# bad
let('user_name') { 'Adam' }
subject('user') { create_user }

# good
let(:user_name) { 'Adam' }
subject(:user) { create_user }
```
EnforcedStyle: strings
```ruby
# bad
let(:user_name) { 'Adam' }
subject(:user) { create_user }

# good
let('user_name') { 'Adam' }
subject('user') { create_user }
```
### Configurable Attributes

Name | Default value | Configurable values
-- | -- | --
EnforcedStyle | symbols | symbols, strings

### References
https://www.rubydoc.info/gems/rubocop-rspec/RuboCop/Cop/RSpec/VariableDefinition

**Comment by MarcelEeken** [comment]
Symbols
