### ISSUE TITLE
RSpec/VariableName

### ISSUE THREAD

**Issue by shannonfuit** [youngcapital/rubocopital#40]
# RSpec/VariableName

Enabled by default | Safe | Supports autocorrection | VersionAdded | VersionChanged
-- | -- | -- | -- | --
Enabled | Yes | No | 1.40 | -

Checks that memoized helper names use the configured style.

### Examples
EnforcedStyle: snake_case (default)
```ruby
# bad
let(:userName) { 'Adam' }
subject(:userName) { 'Adam' }

# good
let(:user_name) { 'Adam' }
subject(:user_name) { 'Adam' }
```
EnforcedStyle: camelCase
```ruby
# bad
let(:user_name) { 'Adam' }
subject(:user_name) { 'Adam' }

# good
let(:userName) { 'Adam' }
subject(:userName) { 'Adam' }
```
### Configurable attributes

Name | Default value | Configurable values
-- | -- | --
EnforcedStyle | snake_case | snake_case, camelCase

### References
https://www.rubydoc.info/gems/rubocop-rspec/RuboCop/Cop/RSpec/VariableName

**Comment by MarcelEeken** [comment]
snake_case

**Comment by shannonfuit** [comment]
snake_case (camelCase in Rails is blasphemy)

**Comment by Raou1d** [comment]
snake_case

**Comment by risc12** [comment]
camelCase

Nah kidding 😄 , snake_case of course.
