### ISSUE TITLE
Lint/NonDeterministicRequireOrder

### ISSUE THREAD

**Issue by Braitenberg** [youngcapital/rubocopital#47]
# Lint/NonDeterministicRequireOrder

Enabled by default | Safe | Supports autocorrection | VersionAdded | VersionChanged
-- | -- | -- | -- | --
Enabled | No | Yes (Unsafe) | 0.78 | -

`Dir[…​]` and `Dir.glob(…​)` do not make any guarantees about the order in which files are returned. The final order is determined by the operating system and file system. This means that using them in cases where the order matters, such as requiring files, can lead to intermittent failures that are hard to debug. To ensure this doesn’t happen, always sort the list.

### Examples
```ruby


# bad
Dir["./lib/**/*.rb"].each do |file|
  require file
end

# good
Dir["./lib/**/*.rb"].sort.each do |file|
  require file
end
```
```ruby


# bad
Dir.glob(Rails.root.join(__dir__, 'test', '*.rb')) do |file|
  require file
end

# good
Dir.glob(Rails.root.join(__dir__, 'test', '*.rb')).sort.each do |file|
  require file
end
```

### References
https://docs.rubocop.org/rubocop/0.87/cops_lint.html#lintnondeterministicrequireorder

**Comment by Raou1d** [comment]
`can lead to intermittent failures that are hard to debug`

While this statement is true, it should never happen, if it does, the developer is to blame as they shouldn't expect implicit requires from an object, rather, the object should do an explicit require for it's dependencies.
