### ISSUE TITLE
Lint/RaiseException

### ISSUE THREAD

**Issue by Braitenberg** [youngcapital/rubocopital#48]
# Lint/RaiseException

Enabled by default | Safe | Supports autocorrection | VersionAdded | VersionChanged
-- | -- | -- | -- | --
Pending | No | Yes (Unsafe) | 0.81 | 0.86

This cop checks for `raise` or `fail` statements which are raising `Exception` class.

You can specify a module name that will be an implicit namespace using `AllowedImplicitNamespaces` option. The cop cause a false positive for namespaced Exception when a namespace is omitted. This option can prevent the false positive by specifying a namespace to be omitted for `Exception`. Alternatively, make `Exception` a fully qualified class name with an explicit namespace.

### examples 
```ruby
# bad
raise Exception, 'Error message here'

# good
raise StandardError, 'Error message here'
```
AllowedImplicitNamespaces: ['Gem']
```ruby


# good
module Gem
  def self.foo
    raise Exception # This exception means `Gem::Exception`.
  end
end
```

### Configurable attributes
Name | Default value | Configurable values
-- | -- | --
AllowedImplicitNamespaces | Gem | Array

### References
* https://docs.rubocop.org/rubocop/0.87/cops_lint.html#lintraiseexception
* https://rubystyle.guide#raise-exception

**Comment by shannonfuit** [comment]
+1 for 
`You can specify a module name that will be an implicit namespace using AllowedImplicitNamespaces option. The cop cause a false positive for namespaced Exception when a namespace is omitted. `, because we do this within modules itself
