### ISSUE TITLE
Lint/StructNewOverride

### ISSUE THREAD

**Issue by Braitenberg** [youngcapital/rubocopital#50]
# Lint/StructNewOverride

Enabled by default | Safe | Supports autocorrection | VersionAdded | VersionChanged
-- | -- | -- | -- | --
Pending | Yes | No | 0.81 | -

This cop checks unexpected overrides of the `Struct` built-in methods via `Struct.new`.

### Examples
```ruby
# bad
Bad = Struct.new(:members, :clone, :count)
b = Bad.new([], true, 1)
b.members #=> [] (overriding `Struct#members`)
b.clone #=> true (overriding `Object#clone`)
b.count #=> 1 (overriding `Enumerable#count`)

# good
Good = Struct.new(:id, :name)
g = Good.new(1, "foo")
g.members #=> [:id, :name]
g.clone #=> #<struct Good id=1, name="foo">
g.count #=> 2
```

### References
https://docs.rubocop.org/rubocop/0.87/cops_lint.html#lintstructnewoverride

**Comment by xtr3me** [comment]
I use structs sometimes when mocking in tests which is hard enough already.
It would be nice if we could exclude this cop within the test / spec directory.

For the linting itself i'm all for it 👍
