### ISSUE TITLE
Performance/AncestorsInclude

### ISSUE THREAD

**Issue by Braitenberg** [youngcapital/rubocopital#53]
# Performance/AncestorsInclude

Enabled by default | Safe | Supports autocorrection | VersionAdded | VersionChanged
-- | -- | -- | -- | --
Pending | Yes | Yes | 1.7 | -

This cop is used to identify usages of `ancestors.include?` and change them to use `⇐` instead.

### Examples
```ruby  
# bad
A.ancestors.include?(B)

# good
A <= B
```

### References
* https://github.com/JuanitoFatas/fast-ruby#ancestorsinclude-vs—​code
* https://docs.rubocop.org/rubocop-performance/cops_performance.html#performanceancestorsinclude

**Comment by MarcelEeken** [comment]
I actually just did the bad thing yesterday 😇

**Comment by LRikkers** [comment]
> I actually just did the bad thing yesterday 😇

I just wanted to mention this to you :p Now change it 😈

**Comment by MarcelEeken** [comment]
Yes boss

**Comment by LRikkers** [comment]
https://gph.is/g/aXY0y6n

**Comment by Raou1d** [comment]
Meh, the  ⇐  operator requires knowledge of the language while the methods can be read by any OOP experienced programmer.
