### ISSUE TITLE
Rails/PluckId

### ISSUE THREAD

**Issue by shannonfuit** [youngcapital/rubocopital#59]
# Rails/PluckId

Enabled by default | Safe | Supports autocorrection | VersionAdded | VersionChanged
-- | -- | -- | -- | --
Pending | No | Yes (Unsafe) | 2.7 | -

This cop enforces the use of ids over pluck(:id) and pluck(primary_key).

### Examples
```ruby
# bad
User.pluck(:id)
user.posts.pluck(:id)

def self.user_ids
  pluck(primary_key)
end

# good
User.ids
user.posts.ids

def self.user_ids
  ids
end
```
### References
https://rails.rubystyle.guide/#ids

**Comment by risc12** [comment]
`#pluck` is defined on the Enumerable-class, while `#ids` is defined on the ActiveRecord-class. So there are cases where this cop will raise even though the code is appropriate.

Let's say I have a response from another service that is an array of objects and I want to pluck the ids, then this cop will raise, even though `#ids` is not available.

**Comment by Raou1d** [comment]
I think Remco is correct, I would also like to add that the auto correct is "unsafe". 

I suggest waiting to see what Rubocop it self does too the default setting.
