### ISSUE TITLE
Rails/ShortI18n

### ISSUE THREAD

**Issue by shannonfuit** [youngcapital/rubocopital#65]
# Rails/ShortI18n

Enabled by default | Safe | Supports autocorrection | VersionAdded | VersionChanged
-- | -- | -- | -- | --
Pending | Yes | Yes | 2.7 | -

This cop enforces that short forms of I18n methods are used: t instead of translate and l instead of localize.

This cop has two different enforcement modes. When the EnforcedStyle is conservative (the default) then only I18n.translate and I18n.localize calls are added as offenses.

When the EnforcedStyle is aggressive then all translate and localize calls without a receiver are added as offenses.

### Examples
```ruby
# bad
I18n.translate :key
I18n.localize Time.now

# good
I18n.t :key
I18n.l Time.now
```
EnforcedStyle: conservative (default)
```ruby
# good
translate :key
localize Time.now
t :key
l Time.now
```
EnforcedStyle: aggressive
```ruby
# bad
translate :key
localize Time.now

# good
t :key
l Time.now
```
### Configurable attributes

Name | Default value | Configurable values
-- | -- | --
EnforcedStyle | conservative | conservative, aggressive

### References
https://rails.rubystyle.guide/#short-i18n

**Comment by MarcelEeken** [comment]
I vote for aggressive

**Comment by Raou1d** [comment]
I vote conservative for readability

**Comment by risc12** [comment]
@Raou1d, shouldn't the cop then not be included at all?

To be honest I would like to have the reverse, have `t` and `l` enforced, but not `I18n.t` and `I18n.l`.

**Comment by Braitenberg** [comment]
We have decided to go with the default configuration (conservative). You are free to configure it differently
