### ISSUE TITLE
Rails/ApplicationController

### ISSUE THREAD

**Issue by martijnbleeker** [youngcapital/rubocopital#8]
## Rails/ApplicationController

Enabled by default | Safe | Supports autocorrection | VersionAdded | VersionChanged
--- | --- | --- | --- | ---
Enabled | Yes | Yes  | 2.4 | -

This cop checks that controllers subclass ApplicationController.

### Examples

```ruby
# good
class MyController < ApplicationController
  # ...
end

# bad
class MyController < ActionController::Base
  # ...
end
```

**Comment by xtr3me** [comment]
How smart is this cop? does it also recognizes Api::V1::ApplicationController as a valid one?
